apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-service
  title: Create New Service
  description: Create a new service with attribution metadata
spec:
  owner: group:default/platform
  type: service
  
  parameters:
    - title: Service Information
      required:
        - name
        - description
      properties:
        name:
          title: Service Name
          type: string
        description:
          title: Description
          type: string
        owner:
          title: Owner
          type: string
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: [Group]
  
  steps:
    - id: fetch
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
    
    # Create attribution metadata file
    - id: create-metadata
      name: Create Attribution Metadata
      action: roadiehq:utils:fs:write
      input:
        path: .backstage/metadata.yaml
        content: |
          createdBy:
            user: ${{ user.entity.metadata.name }}
            email: ${{ user.entity.spec.profile.email }}
            displayName: ${{ user.entity.spec.profile.displayName }}
            timestamp: ${{ "" | now }}
            source: IRS Developer Hub
          component:
            name: ${{ parameters.name }}
            description: ${{ parameters.description }}
            owner: ${{ parameters.owner }}
    
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: github.com?repo=${{ parameters.name }}&owner=po-org
        description: ${{ parameters.description }}
        gitAuthorName: ${{ user.entity.spec.profile.displayName or user.entity.metadata.name }}
        gitAuthorEmail: ${{ user.entity.spec.profile.email or 'backstage@irs.gov' }}
        gitCommitMessage: |
          Initial commit from IRS Developer Hub
          
          Created by: ${{ user.entity.spec.profile.displayName }} (${{ user.entity.metadata.name }})
          Email: ${{ user.entity.spec.profile.email }}
    
    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml
  
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
