# .github/workflows/branch-management.yml
name: Branch Management (Promotion & Sync)

on:
  pull_request:
    types: [closed]
    branches:
      - sssd-rhdh-dev
      - sssd-rhdh-preprod
      - main

jobs:
  # Job 1: Sync main back to the branch that was just merged into
  sync-branch-with-main:
    if: |
      github.event.pull_request.merged == true &&
      (github.base_ref == 'sssd-rhdh-dev' || github.base_ref == 'sssd-rhdh-preprod')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync main to merged branch
        run: |
          TARGET_BRANCH="${{ github.base_ref }}"
          echo "Syncing main back to ${TARGET_BRANCH}"
          git checkout ${TARGET_BRANCH}
          git merge origin/main --no-edit
          git push origin ${TARGET_BRANCH}
        continue-on-error: true

      - name: Report status
        if: failure()
        run: |
          echo "âš ï¸ Could not sync main to ${{ github.base_ref }}"
          echo "Please manually resolve conflicts."

  # Job 2: Create promotion PR when merging up the chain
  create-promotion-pr:
    if: |
      github.event.pull_request.merged == true &&
      (github.base_ref == 'sssd-rhdh-dev' || github.base_ref == 'sssd-rhdh-preprod')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Determine next environment
        id: next-env
        run: |
          if [[ "${{ github.base_ref }}" == "sssd-rhdh-dev" ]]; then
            echo "target=sssd-rhdh-preprod" >> $GITHUB_OUTPUT
          elif [[ "${{ github.base_ref }}" == "sssd-rhdh-preprod" ]]; then
            echo "target=main" >> $GITHUB_OUTPUT
          fi
      
      - name: Create PR to next environment
        if: steps.next-env.outputs.target != ''
        run: |
          gh pr create \
            --base ${{ steps.next-env.outputs.target }} \
            --head ${{ github.base_ref }} \
            --title "ðŸš€ Promote to ${{ steps.next-env.outputs.target }}" \
            --body "Auto-promotion from ${{ github.base_ref }}" \
            || echo "PR may already exist"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Flow:**
```
sbx â†’ PR â†’ dev (merge)
          â†“
      1. dev syncs with main
      2. Auto-creates PR: dev â†’ preprod

       preprod (merge)
          â†“
      1. preprod syncs with main
      2. Auto-creates PR: preprod â†’ main

         main (merge)
          â†“
      (End - no sync needed)
