name: Sync Main to Branches

on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync main to dev
        run: |
          git checkout sssd-rhdh-dev
          git merge origin/main --no-edit
          git push origin sssd-rhdh-dev
        continue-on-error: true

      - name: Sync main to preprod
        run: |
          git checkout sssd-rhdh-preprod
          git merge origin/main --no-edit
          git push origin sssd-rhdh-preprod
        continue-on-error: true

      - name: Report merge conflicts
        if: failure()
        run: |
          echo "⚠️ Some branches could not be synced automatically due to merge conflicts."
          echo "Please manually resolve conflicts and merge main into the affected branches."
