apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: rhdh-scaffolder-api
  description: Red Hat Developer Hub Scaffolder API for template automation
  tags:
    - api
    - scaffolder
    - automation
    - jira-integration
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: production
  owner: platform-team
  definition:
    $text: ./openapi-spec.yaml
