apiVersion: v1
kind: ConfigMap
metadata:
  name: rbac-conditional-policies
  namespace: poteatc-dev
  uid: 9fd16196-f299-4600-a23a-bd2a052006b9
  resourceVersion: '5102619888'
  creationTimestamp: '2025-10-22T11:11:00Z'
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: v1
      time: '2025-10-22T11:11:00Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data': {}
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2025-10-29T00:17:55Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          'f:rbac-conditional-policies.yaml': {}
        'f:immutable': {}
data:
  rbac-conditional-policies.yaml: |+
    ---
    result: CONDITIONAL
    roleEntityRef: role:default/developer
    pluginId: catalog
    resourceType: catalog-entity
    permissionMapping:
      - read
    conditions:
      anyOf:
        # Templates and Components only if owned by guests group
        - rule: IS_ENTITY_OWNER
          resourceType: catalog-entity
          params:
            claims:
              - group:default/vm-team
        # Show ALL of these entity kinds, regardless of ownership
        - rule: IS_ENTITY_KIND
          resourceType: catalog-entity
          params:
            kinds:
              - Group
              - Location
              - Resource
              - Domain
        # Show any entity with visibility: public label
        - rule: HAS_LABEL
          resourceType: catalog-entity
          params:
            label: visibility
            value: public
    ---
    result: CONDITIONAL
    roleEntityRef: role:default/developer
    pluginId: catalog
    resourceType: catalog-entity
    permissionMapping:
      - update
      - delete
    conditions:
      rule: IS_ENTITY_OWNER
      resourceType: catalog-entity
      params:
        claims:
          - group:default/vm-team

binaryData: {}
immutable: false
