apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
  namespace: default
spec:
  type: team
  children: []
  members:
    - development/guest  # â† Explicitly specify namespace/name
