apiVersion: v1
kind: ConfigMap
metadata:
  name: rbac-conditional-policies
  namespace: poteatc-dev
  uid: 9fd16196-f299-4600-a23a-bd2a052006b9
  resourceVersion: '5112946948'
  creationTimestamp: '2025-10-22T11:11:00Z'
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: v1
      time: '2025-10-22T11:11:00Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data': {}
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2025-10-31T01:43:51Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          'f:rbac-conditional-policies.yaml': {}
        'f:immutable': {}
data:
  rbac-conditional-policies.yaml: |-
    ---
    result: CONDITIONAL
    roleEntityRef: role:default/developer
    pluginId: catalog
    resourceType: catalog-entity
    permissionMapping:
      - read
    conditions:
      anyOf:
        # Show entities owned by user or their groups
        - rule: IS_ENTITY_OWNER
          resourceType: catalog-entity
          params:
            claims:
              - $ownerRefs
        
        # Show any entity with visibility: public label
        - rule: HAS_ANNOTATION
          resourceType: catalog-entity
          params:
            annotation: backstage.io/visibility
            value: public
        
        # Allow viewing certain "safe" kinds for everyone
        - rule: IS_ENTITY_KIND
          resourceType: catalog-entity
          params:
            kinds:
              - User
              - Group
              - Location  # ← ADD THIS so you can see Locations to delete them
    ---
    result: CONDITIONAL
    roleEntityRef: role:default/developer
    pluginId: catalog
    resourceType: catalog-entity
    permissionMapping:
      - update
      - delete
    conditions:
      rule: IS_ENTITY_OWNER
      resourceType: catalog-entity
      params:
        claims:
          - $ownerRefs
binaryData: {}
immutable: false
