apiVersion: v1
kind: ConfigMap
metadata:
  name: rbac-conditional-policies
  namespace: poteatc-dev
  uid: 9fd16196-f299-4600-a23a-bd2a052006b9
  resourceVersion: '5093387662'
  creationTimestamp: '2025-10-22T11:11:00Z'
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: v1
      time: '2025-10-22T11:11:00Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data': {}
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2025-10-27T00:44:31Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          'f:rbac-conditional-policies.yaml': {}
        'f:immutable': {}
data:
  rbac-conditional-policies.yaml: |-
    ---
    result: CONDITIONAL
    roleEntityRef: role:default/developer
    pluginId: catalog
    resourceType: catalog-entity
    permissionMapping:
      - read
    conditions:
      anyOf:
        - rule: IS_ENTITY_OWNER
          resourceType: catalog-entity
          params:
            claims:
              - group:default/guests
              - group:default/vm-team
        - rule: HAS_LABEL
          resourceType: catalog-entity
          params:
            label: visibility
            value: public
        - rule: IS_ENTITY_KIND
          resourceType: catalog-entity
          params:
            kinds:
              - Group
              - User
              - Location
binaryData: {}
immutable: false
