apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: vm-team
  description: VM Infrastructure Team
spec:
  type: team
  profile:
    displayName: VM Team
    email: vm-team@yourcompany.com
  children: []
  members:
    - c-nell  # Add your username here
