apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-http-simple
  title: Test HTTP Simple
  description: Test HTTP with correct syntax
spec:
  owner: platform-team
  type: service
  
  parameters:
    - title: Test
      properties:
        test:
          title: Test
          type: string
          default: test

  steps:
    - id: test-catalog
      name: Test Catalog API
      action: http:backstage:request
      input:
        method: GET
        path: /api/catalog/entities
        headers:
          Accept: application/json

  output:
    text:
      - title: Done
        content: Test completed
