apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-api-endpoints
  title: Test API Endpoints
  description: Comprehensive test template for http:backstage:request action
  tags:
    - test
    - debugging
spec:
  owner: platform-team
  type: service
  
  parameters:
    - title: Select API Endpoint to Test
      required:
        - endpoint
      properties:
        endpoint:
          title: API Endpoint
          type: string
          description: Which endpoint do you want to test?
          enum:
            - catalog-entities
            - catalog-locations
            - notifications
            - tech-docs
            - search
          enumNames:
            - 'GET /api/catalog/entities (List all entities)'
            - 'GET /api/catalog/locations (List locations)'
            - 'POST /api/notifications (Send notification)'
            - 'GET /api/techdocs/default/component (TechDocs)'
            - 'GET /api/search/query (Search)'
          default: catalog-entities
        
        notificationRecipient:
          title: Notification Recipient
          type: string
          description: Required if testing notifications (e.g., user:default/c-nell)
          default: user:default/c-nell
        
        notificationMessage:
          title: Notification Message
          type: string
          description: Custom message for notification test
          default: This is a test notification from the API test template

  steps:
    # Test 1: GET Catalog Entities
    - id: test-catalog-entities
      name: Test GET Catalog Entities
      if: ${{ parameters.endpoint === 'catalog-entities' }}
      action: http:backstage:request
      input:
        method: GET
        path: /api/catalog/entities

    # Test 2: GET Catalog Locations
    - id: test-catalog-locations
      name: Test GET Catalog Locations
      if: ${{ parameters.endpoint === 'catalog-locations' }}
      action: http:backstage:request
      input:
        method: GET
        path: /api/catalog/locations

    # Test 3: POST Notifications
    - id: test-notifications
      name: Test POST Notifications
      if: ${{ parameters.endpoint === 'notifications' }}
      action: http:backstage:request
      input:
        method: POST
        path: /api/notifications
        body:
          recipients:
            type: entity
            entityRef: ${{ parameters.notificationRecipient }}
          payload:
            title: API Test Notification
            description: ${{ parameters.notificationMessage }}
            topic: test
            severity: normal

    # Test 4: GET TechDocs
    - id: test-techdocs
      name: Test GET TechDocs
      if: ${{ parameters.endpoint === 'tech-docs' }}
      action: http:backstage:request
      input:
        method: GET
        path: /api/techdocs/default/component

    # Test 5: GET Search
    - id: test-search
      name: Test GET Search
      if: ${{ parameters.endpoint === 'search' }}
      action: http:backstage:request
      input:
        method: GET
        path: /api/search/query?term=component

    # Log the result
    - id: log-result
      name: Log Test Result
      action: debug:log
      input:
        message: |
          API Endpoint Test Completed
          Endpoint tested: ${{ parameters.endpoint }}
          Status: Success

  output:
    text:
      - title: Test Summary
        content: |
          ## API Test Results
          
          **Endpoint Tested:** ${{ parameters.endpoint }}
          **Status:** ✅ Success
          
          The HTTP request completed successfully. Check the scaffolder logs for detailed response data.
          
          ### Tested Endpoint Details:
          - **catalog-entities**: Lists all entities in the catalog
          - **catalog-locations**: Lists all registered locations
          - **notifications**: Sends a test notification to specified user
          - **tech-docs**: Tests TechDocs API availability
          - **search**: Tests search API with a sample query
