apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-http-with-token
  title: Test HTTP with Backend Token
  description: Test HTTP request with authentication
spec:
  owner: platform-team
  type: service
  
  parameters:
    - title: Test
      properties:
        test:
          title: Test
          type: string
          default: test

  steps:
    - id: test-with-token
      name: Test with Backend Token
      action: http:backstage:request
      input:
        method: GET
        path: /api/catalog/entities
        headers:
          Authorization: Bearer ${{ secrets.BACKEND_SECRET }}

  output:
    text:
      - title: Done
        content: Test completed
