apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-http-localhost
  title: Test HTTP with Localhost
  description: Test HTTP request with full URL
spec:
  owner: platform-team
  type: service
  
  parameters:
    - title: Test
      properties:
        test:
          title: Test
          type: string
          default: test

  steps:
    - id: test-with-baseurl
      name: Test with Base URL
      action: http:backstage:request
      input:
        method: GET
        baseUrl: http://localhost:7007
        path: /api/catalog/entities

  output:
    text:
      - title: Done
        content: Test completed
