apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: org-template
  title: Organization Template
  description: Template with organization selection
spec:
  owner: backstage-team
  type: service
  
  parameters:
    - title: Project Information
      properties:
        projectName:
          title: Project Name
          type: string
        orgName:
          title: Organization
          type: string
          enum: [c-nell, po-org]  # Predefined orgs
          enumNames: [Personal Account, Local Org]  # Display names
          description: Select the organization for the repository
        description:
          title: Description
          type: string

  steps:
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: 'github.com?repo={{ parameters.projectName }}&owner={{ parameters.orgName }}'
        gitAuthorName: '{{ user.ref }}'
        gitAuthorEmail: '{{ user.ref }}@yourcompany.com'
