apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: user-aware-template
  title: User Aware Template
  description: A template that uses user information
spec:
  owner: backstage-team
  type: service
  
  parameters:
    - title: Project Information
      properties:
        projectName:
          title: Project Name
          type: string
          description: Name of your project
        description:
          title: Description
          type: string
          description: Project description

  steps:
    - id: debug-user
      name: Debug User Info
      action: debug:log
      input:
        message: 'User ref: {{ user.ref }}'

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        # CORRECT FORMATS:
        repoUrl: 'github.com?repo={{ parameters.projectName }}&owner=your-username'
        # OR
        # repoUrl: 'github.com?repo={{ parameters.projectName }}&owner=your-org-name'
        
        gitAuthorName: '{{ user.ref }}'
        gitAuthorEmail: '{{ user.ref }}@yourcompany.com'
