apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: testing-metadata
  title: Hello World
  description: Says Hello to the user that triggered the template.
spec:
  owner: user:default/punkle
  type: service

  parameters: []
  steps:
    - id: log-hello
      name: Say hello to the logged in user
      action: debug:log
      input:
        message: |
          User Entity: ${{ user.entity.metadata.name }}
          Email Entity: ${{ user.entity.spec.profile.email }}
          Display Name Entity: ${{ user.entity.spec.profile.displayName }}
          User Ref: ${{ user.ref }}
          Name Entity: ${{ user.entity.metadata.name }}
          User Identity Ref: ${{ identity.userEntityRef }}
