apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
spec:
  parameters:
    - title: User Info
      properties:
        # Pre-populate with user data
        authorName:
          title: Author Name
          type: string
          default: '{{ user.ref }}'
        authorEmail:
          title: Author Email  
          type: string
          default: '{{ user.ref }}'

  steps:
    - id: publish
      name: Publish to Git
      action: publish:github
      input:
        repoUrl: 'github.com?repo=my-repo&owner=my-org'
        # Pass user data to git commit
        gitAuthorName: '{{ parameters.authorName }}'
        gitAuthorEmail: '{{ parameters.authorEmail }}'
