apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-author-config
  title: Test Default Author Config
  description: Simple test to verify defaultAuthor is working
spec:
  owner: user:default/guest
  type: service
  
  parameters:
    - title: Repository Info
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  
  steps:
    - id: fetch
      name: Create README
      action: fetch:plain
      input:
        content: |
          # Test Repository
          
          This repo was created to test the defaultAuthor configuration.
          
          Check the git commit author to verify it's working!
        targetPath: ./README.md
    
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        description: Test repository for defaultAuthor config
        # gitAuthorName and gitAuthorEmail should be auto-injected from defaultAuthor config!
  
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.publish.output.entityRef }}
